# YOUR NAME OR TITLE OF YOUR SITE
name: DJ DAR

# YOUR BRAND/PERSONAL TAGLINE
tagline: Howdy, I'm Harsh Trivedi. I'm a passionate Tech Lover from Kanpur, apart from that I'm a Graphic Designer and an OpenSource enthusiast Inspired by Imagination.

# YOUR/BRAND IMAGE URL
Image_URL: https://www.gravatar.com/avatar/0d73468bd0b0258eb61d9358352ecb7b?s=500

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: djdar999
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/in
    Username: harsh98trivedi
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/channel
    Username: UCS3zvA_2r1iGT7MB3NVCGAw
    Color: '#ff0000'
    Icon-Class: fab fa-youtube

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: harsh98trivedi
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # EMAIL
  - Name: Email
    URL: 'mailto:harshtrivedi@duck.com'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

    # TWITCH
  - Name: Twitch
    URL: 'https://twitch.tv'
    Username: harsh98trivedi
    Icon-Class: fab fa-twitch
    Color: '#9147fe'
    Text_Color: '#ffffff'

    # SPOTIFY
  - Name: Spotify
    URL: http://open.spotify.com/user
    Username: 314ihryk3edvtusti6il3oy3x5da
    Color: '#1DB954'
    Icon-Class: fab fa-spotify

    # SOUNDCLOUD
  - Name: SoundCloud
    URL: https://www.soundcloud.com
    Username: harsh98trivedi
    Color: '#FE5000'
    Icon-Class: fab fa-soundcloud

    # CUSTOM LINK
  - Name: Blog
    URL: https://harsh98trivedi.github.io/blog
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
